{"name": "无效用户登录失败", "status": "passed", "description": "测试无效凭据登录应该失败", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "导航到登录页面", "status": "passed", "steps": [{"name": "验证登录页面页面加载", "status": "passed", "start": 1757756800055, "stop": 1757756800123}], "start": 1757756794615, "stop": 1757756800123}], "start": 1757756794615, "stop": 1757756800123}, {"name": "尝试使用无效凭据登录", "status": "passed", "start": 1757756800123, "stop": 1757756805010}, {"name": "验证错误消息", "status": "passed", "start": 1757756805010, "stop": 1757756807067}, {"name": "验证仍在登录页面", "status": "passed", "start": 1757756807067, "stop": 1757756807075}], "attachments": [{"name": "stdout", "source": "26377590-c882-481f-839e-2f6f03b67cbe-attachment.txt", "type": "text/plain"}], "start": 1757756794615, "stop": 1757756807076, "uuid": "4a6a16bd-a63e-4c25-ac9a-040c3ced46c6", "historyId": "31c302b046c1e0441310a7a2a6bcfedd", "testCaseId": "31c302b046c1e0441310a7a2a6bcfedd", "fullName": "tests.test_user_authentication.TestUserAuthentication#test_invalid_user_login", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "用户认证功能"}, {"name": "story", "value": "用户登录"}, {"name": "epic", "value": "AutomationExercise网站测试"}, {"name": "tag", "value": "regression"}, {"name": "tag", "value": "login"}, {"name": "tag", "value": "allure"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_authentication"}, {"name": "subSuite", "value": "TestUserAuthentication"}, {"name": "host", "value": "DESKTOP-D5VPIFL"}, {"name": "thread", "value": "2436-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_authentication"}]}